### ISSUE TITLE
Exporting nodes: error

### ISSUE THREAD

**Issue by wuqui** [RMHogervorst/gephi#4]
I want to write out nodes because I also want to exclude nodes without edges in my graph in Gephi (hope this will work). 

Unfortunately both `gephi_write_nodes()` and `gephi_write_both()` throw errors:

> gephi_write_nodes(net, path=paste0(dir, f_out_nodes))
> Fehler in match.arg(arg = arg, choices = choices, several.ok = several.ok) : 
> 'arg' should be one of “edges”, “vertices”, “both”

I've installed the package from within R from GitHub using `devtools` as recommended in the Readme. `gephi_write_edges()` works fine.

**Comment by RMHogervorst** [comment]
Let me check tonight will come back at you tomorrow

**Comment by RMHogervorst** [comment]
I found the bug, thanks for letting me know!

**Comment by wuqui** [comment]
De nada, thanks for fixing it so quickly! :)
